### ISSUE TITLE
source Code 

### ISSUE THREAD

**Issue by vaddekrishn** [vaddekrishn/CIS-634#7]
Done testing the login view and the database of the application for users names and passwords working good able to create new user and password. The UI able to re-adject according to the screen. The code is cleaned. Need the source code for the admin page

**Comment by savanrao** [comment]
Is the testing done??

**Comment by vaddekrishn** [comment]
yes Sava, I will send you the clean code ASAP !

**Comment by savanrao** [comment]
I guess the issue is resolved, so i will be closing it

**Comment by vaddekrishn** [comment]
Sava can you give me the update on the elements we discussed on the zoom call please.

**Comment by savanrao** [comment]
My name is not sava 🤦🏻

**Comment by vaddekrishn** [comment]
😅 sava_n

**Comment by savanrao** [comment]
And I have sent all the updates on the email can u check
